name: Update Dragonholic Feed

on:
  schedule:
    - cron: '*/5 * * * *'  # Run every 5 minutes; adjust as needed
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update_feed:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install feedparser PyRSS2Gen requests beautifulsoup4

      - name: Run Feed Generator
        run: python dh_feed_generator.py

      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add dh_modified_feed.xml
          git commit -m "Update XML feed" || echo "No changes to commit"
          git pull --rebase
          git push
