name: Update Dragonholic Locked Feed

on:
  schedule:
    - cron: '*/10 * * * *'  # Run every half an hour
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update_feed:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install requests beautifulsoup4 PyRSS2Gen

      - name: Download Latest Mapping File
        run: |
          curl -L https://raw.githubusercontent.com/dholicrssfeed/dragonholic-modified-feed/main/dh_mappings.py -o dh_paid_mappings.py

      - name: Run Feed Generator
        run: python dh_paid_feed_generator.py

      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add dh_paid_feed.xml
          git commit -m "Update paid XML feed" || echo "No changes to commit"
          git push
